[tool.poetry]
name = "tests"
version = "0.1.0"
description = ""
authors = ["0Kit <kostyajog@mail.ru>"]
packages = [
    { include = "app" }
]

[tool.poetry.dependencies]
python = "^3.8"
aiogram = "2.11.2"
aioredis = "1.3.1"
alembic = "1.4.3"
environs = "9.3.0"
gino = "1.0.1"
loguru = "0.5.3"
sqlalchemy = "1.3.22"
psycopg2-binary = "^2.8.6"
appdirs = "1.4.4"

[tool.poetry.dev-dependencies]
isort = "5.6.4"
flake8 = "3.8.4"
black = "20.8b1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
[tool.isort]
line_length = 99
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
skip = [
    'app/__main__.py',
]

[tool.black]
skip-string-normalization = true
line-length = 99
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | dist
  | .env
)/
| /pgdata
'''
